import type { PaperAnalysis } from "../data/sampleData";

export function generateReport(paper: PaperAnalysis) {
  const content = `# Research Paper Analysis Report
Generated by ResearchAI Analyzer — ${new Date().toLocaleDateString()}

---

## Paper Information

**Title:** ${paper.title}

**Authors:** ${paper.authors.map((a) => `${a.name} (${a.affiliation})`).join(", ")}

**Year:** ${paper.year}

**Journal/Venue:** ${paper.journal}

**DOI:** ${paper.doi}

**Pages:** ${paper.pages}

**Word Count:** ${paper.wordCount.toLocaleString()}

**Citations:** ${paper.citations.toLocaleString()}

---

## Impact Scores

| Metric | Score |
|--------|-------|
| Impact Score | ${paper.impactScore}/100 |
| Novelty Score | ${paper.noveltyScore}/100 |
| Readability Score | ${paper.readabilityScore}/100 |

---

## Abstract

${paper.abstract}

---

## Key Findings

${paper.keyFindings.map((f, i) => `${i + 1}. ${f}`).join("\n")}

---

## Research Methodology

${paper.methodology}

### Methodology Steps

${paper.methodologySteps.map((s, i) => `**Step ${i + 1}: ${s.title}**\n${s.description}`).join("\n\n")}

---

## Datasets Used

${paper.datasets.map((d) => `- **${d.name}** — ${d.size} (${d.type}, Source: ${d.source})`).join("\n")}

---

## Algorithms & Models

${paper.algorithms.map((a) => `### ${a.name}\n- **Type:** ${a.type}\n${a.accuracy ? `- **Performance:** ${a.accuracy}\n` : ""}- **Description:** ${a.description}`).join("\n\n")}

---

## Top Keywords

${paper.keywords
  .sort((a, b) => b.frequency - a.frequency)
  .slice(0, 10)
  .map((k) => `- **${k.word}** — Frequency: ${k.frequency}, Relevance: ${k.relevance}%, Category: ${k.category}`)
  .join("\n")}

---

## AI-Generated Summary

${paper.summary}

---

## Section Breakdown

${paper.sections.map((s) => `| ${s.title} | ${s.wordCount} words |`).join("\n")}

---

*Report generated by ResearchAI Analyzer — M.Tech CSE Portfolio Project*
*${new Date().toISOString()}*
`;

  const blob = new Blob([content], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `research-analysis-${paper.id}-${Date.now()}.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
